### ISSUE TITLE
Blocking channels

### ISSUE THREAD

**Issue by huonw** [aturon/crossbeam#10]
It can be useful to have channels that can block when they're empty (or full, if they're size limited).

**Comment by aturon** [comment]
It should be relatively easy to add this to the existing channels universally -- i.e., it shouldn't come at a cost to non-blocking uses, and we can provide a `try_pop`-like method for the nonblocking version.

**Comment by sorear** [comment]
Generally you're not supposed to sleep in RCU read-side critical sections.  A blocking channel could be problematic if it holds the current epoch open for all other users.

**Comment by huonw** [comment]
A channel doesn't need to hold the epoch open while blocked. An implementation could look something like `loop { match non_blocking.pop()  { Some(x) => return x, None => block() } }`, i.e. it only holds the epoch inside `pop`.
