### ISSUE TITLE
Does the TreiberStack algorithm contain a specific race condition?

### ISSUE THREAD

**Issue by seeekr** [aturon/crossbeam#104]
Hey there,

quick question here: I'm researching what crossbeam has to offer. On TreiberStack I'm finding that Wikipedia says that there is an issue with correctness here, quoting [Link](https://en.wikipedia.org/wiki/Treiber_Stack#Correctness):

> The Treiber stack is a classical example of an incorrect solution. It suffers from the ABA problem. When a process is about to remove an element from the stack (just before the compare and set in the pop routine below) another process can change the stack such that the head is the same, but the second element is different. The compare and swap will set the head of the stack to the old second element in the stack mixing up the complete data structure.

Could someone shed some light on this (potential) issue? Is the Wikipedia entry simply incomplete for not mentioning ways in which actual implementations of the algorithm successfully work around this and thus do in fact produce correct results?

I did find a bit more info on this in Aaron's blog here: https://aturon.github.io/blog/2015/08/27/epoch/#lock-free-data-structures

To me the bit about not freeing `Node`s (immediately) seems to coincide with what WP says about the correctness issue (especially on the page about the [ABA problem](https://en.wikipedia.org/wiki/ABA_problem)), and as such I might reason that maybe this is the missing piece and why the algorithm is correct in this implementation after all. But I'd be guessing at this point and would have to actually read the source code and do the critical thinking before forming an actual understanding of what's going on.

Lazy (or otherwise-busy) as I am I thought I'd ask about this, seeing as the same question might pop up for other somewhat-diligent crossbeam users and so having a piece of public info on this would be great :)

Cheers & thanks!

**Comment by stjepang** [comment]
The epoch mechanism ensures this: After you enter an epoch and before you exit it, any node that is reachable within the stack will not be freed.
In other words, ABA can't happen.

Treiber stack suffers from ABA only if you don't protect it with a memory reclamation mechanism. Some methods of lock-free memory reclamation are:

* read copy update
* epochs
* tagged hazard pointers
* pass the buck
* drop the anchor
* differential reference counting

I suggest looking up those terms on the internet - there's plenty of good articles.
Hope that helps! :)

**Comment by seeekr** [comment]
Excellent! Thanks for confirming & further elucidating!
