### ISSUE TITLE
Is MsQueue missing memory barriers?

### ISSUE THREAD

**Issue by sorear** [aturon/crossbeam#12]
I'm looking over the MsQueue code to practice reasoning about memory barriers, and I see a couple things that appear odd:

* I don't think any of these memory orderings are required to be effective.  Per the LLVM spec, `Acquire` only does something when paired with `Release` and conversely, but MsQueue only uses `Release` and `Relaxed` on the `next` pointers and `Acquire` and `Relaxed` on the `head` and `tail` pointers.  So I think the implementation is allowed to replace all of the orderings with `Relaxed`. ?

* If we ignore that and pretend `Acquire` can synchronize with `Relaxed`, `pop()` is still doing a `Relaxed` fetch of `head.next` and then reading from the next record's `data` without additional memory barriers, which could get uninitialized memory on Alpha ?  (It looks like this is the kind of thing `memory_order_consume` is for, as this is technically stronger than `Relaxed` but still requires no barriers on common hardware.  Wonder when LLVM/Rust will get it.)

**Comment by aturon** [comment]
You're correct. I've fixed the orderings -- thanks!
