### ISSUE TITLE
Break out scoped threads as a stable crate

### ISSUE THREAD

**Issue by bluss** [aturon/crossbeam#3]
Would love to use this in stable

**Comment by RalfJung** [comment]
Same here.

Alternatively, crossbeam could follow the pattern of some other crates and put all features that require unstable behind a feature "unstable", such that the part of crossbeam that compiles with stable, can be used on stable.

**Comment by vberger** [comment]
Ah big :+1: on this

**Comment by bluss** [comment]
Talked with aturon, and I had forgot as I reported this issue, that scoped threads depend on a borrowck bugfix that's only in Rust 1.4 (not in stable yet). I hope we can manage this as soon Rust 1.4 comes out.

**Comment by aturon** [comment]
Crossbeam now runs on stable Rust by default!

I've added a `nightly` feature which may offer a slight performance increase (due to being able to use statics rather than concurrent initialization).

This also instigated a fairly nice internal refactoring.

Next up, more docs around scoped.

**Comment by bluss** [comment]
Does it run on rust 1.3? Might need to mark scoped threads unsafe just like the scoped threadpool crate did in that case.
