### ISSUE TITLE
Check MsQueue for validity

### ISSUE THREAD

**Issue by schets** [aturon/crossbeam#46]
Both @msullivan and I have gotten assertion errors in the stress-msq.rs test - for me, it takes a while, so this isn't an easy condition to hit, but this shouldn't ever happen. The assertion that we have both seen fail is the [new > cur == true assertion](https://github.com/aturon/crossbeam/blob/master/src/bin/stress-msq.rs#L28).

**Comment by schets** [comment]
FWIW, the stress test runs with with SegQueue - it's been going strong for 14 hours on my machine whereas the MsQueue would fail within 20 min.

**Comment by aturon** [comment]
Are you hitting these assertions with the current master branch, or only when reverting to local bags?

I haven't seem them in current master, and was assuming that I was seeing them before due to problems with memory reclamation leading to ABA bugs.

When I was debugging the bag issue, I worked with a simplified version of the MsQueue code (with the blocking support stripped out) to help ensure the bug wasn't there. It was still producing assertion violations, as well as segfaults.

Note that MsQueue ends up stressing memory reclamation quite a bit more than SegQueue, since the latter does block (de)allocation. So it would make sense for hard-to-hit reclamation bugs showing up in MsQueue more quickly.

**Comment by schets** [comment]
I was seeing them in master. I'm not completely sure if this was a memory issues - I'll edit the comment to be more specific, but the test was pulling elements from the queue out of order.

**Comment by aturon** [comment]
OK, very interesting to know you're seeing this on master; I'll try harder to duplicate on my end as well.

Do you see what I mean about the ABA problem, though? Basically I'm saying that a bug in the epoch system could surface as broken invariants in the queue.

**Comment by schets** [comment]
Ooooh yeah I had forgotten about that - that would explain why this is so rare, the sequence of events to get this might be very, very rare then - there would of had to be a sequence which not only caused the GC to run early, but then a corresponding malloc call which returned the same pointer in such a way that it triggered ABA. I guess an extremely unfortunate descheduling could cause that. I wonder if the test could have continued if it didn't panic on the assertion failure then.

I'll double check that I was on master when I get back to the test machine. I know for sure that it had the participant fix.

How long are you running the test for? The removal of local bags did have a decent performance hit which would decrease the pop rate. In addition to lowering the error frequency, it may slow down the operation enough to make error occurrences much rarer. Also, memory is much more likely to be deallocated by a different thread that it was allocated on, which may lower the rate at which it's immediately reused.

**Comment by msullivan** [comment]
I've been poking around some at this, including a variant where I log the invariant violation without exiting. The behavior is bizarre. I've observed a thread dequeue 82101, then 82001, 82002, all the way back to 82101 again, without crashing.

This is in a branch in which I have `unlinked` poisoning the memory with `0xcc` too.

**Comment by msullivan** [comment]
OK, I think it is almost certainly a problem with the core epoch code and not with the queues. I made `free` poison the memory with `0xcc` but not actually free it and can get the queue to spit out poisoned values as its output. This indicates pretty clearly that memory is getting freed while it is still being used.

**Comment by msullivan** [comment]
Got it, I think. 

See https://github.com/aturon/crossbeam/blob/208bf821e70d432d18b2c1284da4aa2eb7bb46fc/src/mem/epoch/participant.rs#L102-L105

Here, `self.epoch` is advanced to `new_epoch` immediately before collecting the garbage from `new_epoch+1`. But as soon as `self.epoch` is advanced to `new_epoch`, the global epoch can be advanced to `new_epoch+1` and garbage will get put into the `new_epoch+1` bag that is about to be collected.

**Comment by schets** [comment]
Interesting! I'm running a test now that has 4 global bags - the bag collected is new_epoch - 2, which will be one ahead of new_epoch + 1 (the maximum possible global epoch). This seems like a suboptimal solution, but it should work if I'm thinking through it right.

**Comment by msullivan** [comment]
I think that shouldn't be necessary. I think it should be fine to just do the local epoch update *after* the collection. I'm planning to put up a PR as soon as I've let the test run a bit more.

**Comment by schets** [comment]
Actually, you're right - nevermind.

**Comment by schets** [comment]
Oops didn't mean to close this. Sometimes clicks just happen.
