### ISSUE TITLE
spawn_unsafe should require that F: Send

### ISSUE THREAD

**Issue by jonhoo** [aturon/crossbeam#54]
The `spawn_unsafe` method in Crossbeam should include a bound on the function `f: F` that it is also `Send`. Otherwise, you may end up calling functions that access non-thread-safe things like `UnsafeCell`. This also brings the definition more in line with that of [`std::thread::spawn`](https://doc.rust-lang.org/std/thread/fn.spawn.html). Specifically, the signature should be:

```rust
pub unsafe fn spawn_unsafe<'a, F>(f: F) -> JoinHandle<()> 
where F: FnOnce() + Send + 'a
```

**Comment by aturon** [comment]
The bounds were deliberately left off to provide a maximally flexible, unsafe spawning function -- i.e., to cover even the case where you wanted to work with a non-`Send` closure unsafely.

That said, the flexibility isn't needed for scoped threads, and of course does add to the overall danger of this function. Arguably, this treatment of `Send` might be better accomplished through a newtype wrapper anyway. So I'm open to adding the bound.

**Comment by jonhoo** [comment]
An alternative might be to provide two unsafe functions instead of one, where one requires `Send`, and its use is recommended where possible.

**Comment by aturon** [comment]
Given that there's not a pressing need for a version without `Send`, I'd accept a PR that just added `Send` to the current method.

**Comment by jonhoo** [comment]
PR submitted: #55.
