### ISSUE TITLE
Method name consistency

### ISSUE THREAD

**Issue by chills42** [aturon/crossbeam#68]
I noticed that the [Treiber stack pop method](https://github.com/aturon/crossbeam/blob/51522e2ac2d0266d64fa7969d6161d240fdd90ec/src/sync/treiber_stack.rs#L48) is returning an Option.  For [consistency reasons](https://github.com/aturon/crossbeam/blob/51522e2ac2d0266d64fa7969d6161d240fdd90ec/src/sync/ms_queue.rs#L230) it would be preferable for that to be named `try_pop`.

The downside here is that it would be a breaking change, but since it's still a WIP, it seems like a reasonable change (likely with some kind of temporary deprecation warning).

**Comment by chills42** [comment]
I'd be happy to do a PR if that makes sense.

**Comment by aturon** [comment]
Yep, this was just an oversight, and I'd be happy to take a PR.

**Comment by chills42** [comment]
Here we go: https://github.com/aturon/crossbeam/pull/69
