### ISSUE TITLE
MsQueue .pop() panics on Windows with "You can't return Response::done() from Machine::create() until new release of slab crate."

### ISSUE THREAD

**Issue by LaylConway** [aturon/crossbeam#79]
As the title says, this function seems to work fine on linux but panics on windows.
Project code for reference:
https://github.com/carbidegames/sapphire-hail/blob/745f4d9725dd519bd473a45676c205e575fe73eb/clockwork/src/clockwork.rs#L70

**Comment by LaylConway** [comment]
This is an issue that blocks any web development using my framework on windows.

**Comment by schets** [comment]
I'm pretty sure the panic occurs [here](https://github.com/tailhook/rotor/blob/master/src/handler.rs). Looks like right around [this condition and the next](https://github.com/tailhook/rotor/blob/master/src/response.rs#L190) will cause the error to be raised by returning a failed result. Crossbeam doesn't use the slab crate or have Response/Machine structs so the error isn't from the Crossbeam crate itself.

If you've tried this with a different queue and the result is different, that would be extremely interesting. Looking at what causes the issue, it appears that rotor to get along with Windows. Does it log the error from line 191 of rotor/src/response.rs?

**Comment by LaylConway** [comment]
I haven't had a chance to test this yet but it seems that it indeed is a hyper issue, not a crossbeam issue.
