### ISSUE TITLE
`ArcCell` to accept `?Sized`.

### ISSUE THREAD

**Issue by dpc** [aturon/crossbeam#90]
It seems to me that since it uses `Arc` underneath, `Sized` is not required and was added implicitly.

**Comment by apasel422** [comment]
It is required, because an `Arc` containing an unsized value takes up two words (the data pointer and the slice length or trait vtable pointer) and therefore doesn't fit in an `AtomicUsize`.

**Comment by dpc** [comment]
Oh. Ok then. Thank you. :)
