### ISSUE TITLE
Incorrect atomic orderings in MS Queue?

### ISSUE THREAD

**Issue by carllerche** [aturon/crossbeam#97]
I can't see how the signal access is safe:

thread::park permits spurious wake ups, so it can't be used to guard memory.

Producer: https://github.com/aturon/crossbeam/blob/master/src/sync/ms_queue.rs#L176-L177
Consumer: https://github.com/aturon/crossbeam/blob/master/src/sync/ms_queue.rs#L298-L301

I just don't see how that is safe. I think it happens to work most of the time because x86 basically provides implicit acq / rel semantics (though the compiler could reorder). Also, the current implementation of thread::park() / unpark() happens to be strong today and there will *rarely* be a random thread that issues an unpark (though it is possible).

**Comment by rocallahan** [comment]
I think I actually hit this on x86. https://robert.ocallahan.org/2018/08/for-first-time-in-my-life-i-tracked.html
